version: 2.0
jobs:
  build:
    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Tests
          command: yarn test

      - run:
          name: Building package...
          command: yarn build