version: 2.0
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: node:latest
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages

    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Tests
          command: yarn test

      - run:
          name: Building package...
          command: yarn build

      - deploy:
          name: Deploy docs
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              yarn docz:build

              cp -a docs/. out/.

              mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
              cd out

              git add -A
              git commit -m "Deploy of docs to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin $TARGET_BRANCH
            fi
